/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imua.development;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kamau
 */
public class AccountRegistration extends javax.swing.JFrame {

    private String filePath;
    private String fileurlp = null;
    private String nametitle = null;
    private String maritalStatus = null;
    String toCombo[];
    String toAccountsTypes[];
    private String group = null;
    private String accounttype = null;
  String accounts[];
  String groups[];
    /**
     * Creates new form AccountRegistration
     */
    public AccountRegistration() {
        initComponents();
         findUsers();
         findGroups();
        txtFieldsCntrl();
        accountsTypes();
        setTilteImage();
  
    }
private void setTilteImage(){
     Methods n=new Methods();
    String t= n.setTitle();
    this.setTitle(t);
    String i=n.setIconImage();
    this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(i)));
}
    private void attachImage() {
        try {

            JFileChooser chooser = new JFileChooser();
            FileFilter ft = new FileNameExtensionFilter("Image Files", new String[]{"jpg", "png", "jpeg"});

            chooser.addChoosableFileFilter(ft);

            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();

            this.filePath = f.getAbsolutePath().toString();
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(this.filePath));
                this.fileurlp = this.filePath.replace("\\", "\\\\");
            } catch (IOException e) {
                e.printStackTrace();
            }
            Image dimg = img.getScaledInstance(this.img.getWidth(), this.img.getHeight(), 4);

            ImageIcon icon = new ImageIcon(dimg);
            this.img.setText("");
            this.img.setIcon(icon);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "error loading image ");
        }
    }
  public void findUsers()
  {
      Methods m=new Methods();
    ArrayList<String> usersList =  m.ListUsers();
   accounts=new String[usersList.size()];
   usersList.toArray(accounts);
  }
   public void findGroups()
  {
      Methods m=new Methods();
    ArrayList<String> usersList =  m.ListUsersGroups();
   groups=new String[usersList.size()];
   usersList.toArray(groups);
   //JOptionPane.showMessageDialog(null, groups[0]);
  }

    private void accountsTypes() {
       // String accounts[] = {"Regular Acc", "Projects Acc", "Table Acc"};
        toAccountsTypes = accounts;
        setAccountModel();
    }

    private void setAccountModel() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("choose");
        for (int a = 0; a < toAccountsTypes.length; a++) {

            jComboBox1.addItem(toAccountsTypes[a]);
        }
    }

    private void groupnames() {
       // String namesdb[] = {"eric", "kogi"};
        toCombo = groups;
        setModel();

    }

    private void setModel() {
        jComboBoxGroup.removeAllItems();
        jComboBoxGroup.addItem("choose");
        for (int a = 0; a < toCombo.length; a++) {

            jComboBoxGroup.addItem(toCombo[a]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtOtherName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ComboSalutation = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtSirName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTown = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCounty = new javax.swing.JTextField();
        ComboMarital = new javax.swing.JComboBox();
        txtSirSpouceName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtSpouceName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtSpouceMobile = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtSpouceID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtAccountNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxGroup = new javax.swing.JComboBox<>();
        btnAttachPhoto = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtPeronId = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        jLabel3.setText("Tenant Information");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 80));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        jLabel4.setText("Customer Registration Information");

        jLabel1.setText("Sir Name");

        txtOtherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Title");

        ComboSalutation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select --", "Mr.", "Mrs", "Ms", "Doc", "Prof" }));
        ComboSalutation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboSalutationItemStateChanged(evt);
            }
        });
        ComboSalutation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSalutationActionPerformed(evt);
            }
        });

        jLabel5.setText("Other Name");

        txtSirName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSirNameActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel6.setText("National ID");

        txtPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNoActionPerformed(evt);
            }
        });

        jLabel7.setText("Mobile No.");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        jLabel10.setText("Address");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel13.setText("County");

        txtTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTownActionPerformed(evt);
            }
        });

        jLabel14.setText("Town");

        txtCounty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountyActionPerformed(evt);
            }
        });

        ComboMarital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Single", "Married", "Widowed", "Divorced" }));
        ComboMarital.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboMaritalItemStateChanged(evt);
            }
        });
        ComboMarital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMaritalActionPerformed(evt);
            }
        });

        txtSirSpouceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSirSpouceNameActionPerformed(evt);
            }
        });

        jLabel17.setText("Optional");

        txtOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOccupationActionPerformed(evt);
            }
        });

        jLabel18.setText("Occupation");

        jLabel19.setText("Marital Status");

        jLabel20.setText("Spouce Sir Name");

        jLabel21.setText("Spouce Other Name");

        txtSpouceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpouceNameActionPerformed(evt);
            }
        });

        jLabel22.setText("Spouce ID No.");

        txtSpouceMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpouceMobileActionPerformed(evt);
            }
        });

        jLabel23.setText("Mobile No.");

        txtSpouceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpouceIDActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtAccountNo.setText("Auto");
        txtAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNoActionPerformed(evt);
            }
        });

        jLabel16.setText("Account No.");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Account Type");

        jComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose" }));
        jComboBoxGroup.setEnabled(false);
        jComboBoxGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxGroupItemStateChanged(evt);
            }
        });

        btnAttachPhoto.setText("Attach Photo");
        btnAttachPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachPhotoActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(jLabel8))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOtherName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ComboSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSirName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(btnAttachPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(txtPeronId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSpouceID, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSirSpouceName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtSpouceName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSpouceMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboMarital, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(26, 26, 26)
                                        .addComponent(jComboBoxGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addGap(8, 8, 8)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeronId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(6, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSirName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOtherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboMarital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(35, 35, 35)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSirSpouceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSpouceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSpouceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSpouceMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnClear)
                                .addComponent(btnCancel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAttachPhoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemove)))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOtherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherNameActionPerformed

    private void txtSirNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSirNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSirNameActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtTownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTownActionPerformed

    private void txtCountyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountyActionPerformed

    private void txtSirSpouceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSirSpouceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSirSpouceNameActionPerformed

    private void txtOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOccupationActionPerformed

    private void txtSpouceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpouceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpouceNameActionPerformed

    private void txtSpouceMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpouceMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpouceMobileActionPerformed

    private void txtSpouceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpouceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpouceIDActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     Random rand =new Random();
    n= (rand.nextInt(5000)+1000);
     
     txtAccountNo.setText(String.valueOf(n));
    
        
        check();
       // insertUserDetails();
    }//GEN-LAST:event_btnSaveActionPerformed
 int n;
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Main.a = 1;
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNoActionPerformed

    }//GEN-LAST:event_txtAccountNoActionPerformed

    private void ComboSalutationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSalutationActionPerformed

    }//GEN-LAST:event_ComboSalutationActionPerformed

    private void ComboMaritalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMaritalActionPerformed

    }//GEN-LAST:event_ComboMaritalActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Main.a = 1;

    }//GEN-LAST:event_formWindowClosed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        //  String choice[]={"Choose","Table acc","Individual acc","Regular acc"};
       // String accounts[] = {"Regular Acc", "Projects Acc", "Table Acc"};
        if (evt.getItem() == "choose" && evt.getStateChange() == ItemEvent.SELECTED) {
           //jComboBoxGroup.setEnabled(false);
            accounttype = null;
            group=null;
//        } else if (evt.getItem().toString().contains("Table")||evt.getItem().toString().contains("Group")&& evt.getStateChange() == ItemEvent.SELECTED) {
//           // jComboBoxGroup.setEnabled(true);
//            accounttype = evt.getItem().toString();
//            groupnames();
        } else {
           jComboBoxGroup.setEnabled(true);
           // group=null;
           groupnames();
            accounttype = evt.getItem().toString();
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void btnAttachPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachPhotoActionPerformed
        attachImage();
    }//GEN-LAST:event_btnAttachPhotoActionPerformed

    private void ComboSalutationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboSalutationItemStateChanged
        String[] title = {"--Select --", "Mr.", "Mrs", "Ms", "Doc", "Prof"};
        if (evt.getItem() == title[1] && evt.getStateChange() == ItemEvent.SELECTED) {
            nametitle = title[1];

        }
        if (evt.getItem() == title[2] && evt.getStateChange() == ItemEvent.SELECTED) {
            nametitle = title[2];

        }
        if (evt.getItem() == title[3] && evt.getStateChange() == ItemEvent.SELECTED) {
            nametitle = title[3];

        }
        if (evt.getItem() == title[4] && evt.getStateChange() == ItemEvent.SELECTED) {
            nametitle = title[4];

        }
        if (evt.getItem() == title[5] && evt.getStateChange() == ItemEvent.SELECTED) {
            nametitle = title[5];

        }
        if (evt.getItem() == title[0] && evt.getStateChange() == ItemEvent.SELECTED) {
            nametitle = null;

        }

    }//GEN-LAST:event_ComboSalutationItemStateChanged

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        img.setIcon(null);
        filePath = null;
        fileurlp = null;

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void ComboMaritalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboMaritalItemStateChanged
        String choice[] = {"--Select--", "Single", "Married", "Widowed", "Divorced"};

        if (evt.getItem() == choice[1] && evt.getStateChange() == ItemEvent.SELECTED) {
            maritalStatus = choice[1];
            disable();
        }
        if (evt.getItem() == choice[2] && evt.getStateChange() == ItemEvent.SELECTED) {
            maritalStatus = choice[2];
            enable();
        }
        if (evt.getItem() == choice[3] && evt.getStateChange() == ItemEvent.SELECTED) {
            maritalStatus = choice[3];
            disable();
        }
        if (evt.getItem() == choice[4] && evt.getStateChange() == ItemEvent.SELECTED) {
            maritalStatus = choice[4];
             disable();
        }
        if (evt.getItem() == choice[0] && evt.getStateChange() == ItemEvent.SELECTED) {
            maritalStatus = null;
            disable();

        }
    }//GEN-LAST:event_ComboMaritalItemStateChanged
public void disable(){
    txtSirSpouceName.setEditable(false);
    txtSpouceName.setEditable(false);
    txtSirSpouceName.setEnabled(false);
    
    txtSpouceName.setEnabled(false);
    txtSpouceID.setEditable(false);
     txtSpouceID.setEnabled(false);
    txtSpouceMobile.setEditable(false);
    txtSpouceMobile.setEnabled(false);
}
public void enable(){
    txtSirSpouceName.setEditable(true);
    txtSpouceName.setEditable(true);
    txtSirSpouceName.setEnabled(true);
    
    txtSpouceName.setEnabled(true);
    txtSpouceID.setEditable(true);
     txtSpouceID.setEnabled(true);
    txtSpouceMobile.setEditable(true);
    txtSpouceMobile.setEnabled(true);
}
    
    public void check(){
        
        
    try{
     int y=Integer.valueOf(txtPhoneNo.getText()) ;
     int u= Integer.valueOf(txtId.getText());
     
        if(
                //txtSirName.getText().isEmpty()||
        txtOtherName.getText().isEmpty()||
        txtId.getText().isEmpty()||
        txtPhoneNo.getText().isEmpty()||
     //   txtEmail.getText().isEmpty()||
        txtAddress.getText().isEmpty()||
        txtCounty.getText().isEmpty()||
        txtTown.getText().isEmpty()||
        txtOccupation.getText().isEmpty()||
       // txtSirSpouceName.getText().isEmpty()||
       // txtSpouceName.getText().isEmpty()||
       // txtSpouceID.getText().isEmpty()||
       // txtSpouceMobile.getText().isEmpty()||
      //  img.getIcon()==null||
      //  filePath == null||
      //  fileurlp == null||
      //  ComboSalutation.getSelectedIndex()==0||
        ComboMarital.getSelectedIndex()==0||
        jComboBox1.getSelectedIndex()==0||
       jComboBoxGroup.getSelectedIndex()==0)
            
        {
            JOptionPane.showMessageDialog(null, "101 One or More Fields Missing");
        }
        else{
            insertUserDetails();
            // JOptionPane.showMessageDialog(null, "CREATED ACCOUNT NO IS"+n);
        }
    }catch(Exception n){
         JOptionPane.showMessageDialog(null, "ERROR 102");
    }
}
    private void jComboBoxGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxGroupItemStateChanged
        String[] choice = toCombo;
        if (evt.getItem() != "choose" && evt.getStateChange() == ItemEvent.SELECTED) {
            group = evt.getItem().toString();

        } else {
            group = null;
        }

    }//GEN-LAST:event_jComboBoxGroupItemStateChanged

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed
 public void fetchUserDetails(String value, String where) {

        try {
            Methods m = new Methods();
            Connection con = m.getConnection();
            Statement st = con.createStatement();
            String searchQuery = "SELECT * FROM `users` WHERE `" + where + "` = '" + value + "'";
            ResultSet rs = st.executeQuery(searchQuery);
            while (rs.next()) {
                txtSirName.setText(rs.getString("fname"));
                txtOtherName.setText(rs.getString("sname"));
                txtPhoneNo.setText(rs.getString("phone"));
                 txtAddress.setText(rs.getString("address"));
                txtTown.setText(rs.getString("town"));
               // txtOccupation.setText(rs.getString("acounttype"));
                txtCounty.setText(rs.getString("county"));
                txtOccupation.setText(rs.getString("occupation"));
                txtSirSpouceName.setText(rs.getString("spaucefname"));
        txtSpouceName.setText(rs.getString("spaucesname"));
        txtSpouceID.setText(rs.getString("spauceid"));
        txtSpouceMobile.setText(rs.getString("spaucephone"));
        txtAccountNo.setText(rs.getString("accountno"));
        
        
        
 //txtSirName.setText(null);
      //  txtOtherName.setText(null);
      //  txtId.setText(null);
//        txtPhoneNo.setText(null);
//        txtEmail.setText(null);
//        txtAddress.setText(null);
//        txtCounty.setText(null);
//        txtTown.setText(null);
//        txtOccupation.setText(null);
//        txtSirSpouceName.setText(null);
//        txtSpouceName.setText(null);
//        txtSpouceID.setText(null);
//        txtSpouceMobile.setText(null);
//        txtAccountNo.setText("Auto");
//        img.setIcon(null);
//        filePath = null;
//        fileurlp = null;
//        ComboSalutation.setSelectedIndex(0);
//        ComboMarital.setSelectedIndex(0);
//        jComboBox1.setSelectedIndex(0);
//        jComboBoxGroup.setSelectedIndex(0);
              
            }
            st.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        deleteUserDetails(txtPeronId.getText());
    }//GEN-LAST:event_jButton1ActionPerformed
   public void deleteUserDetails(String id){
        Methods n=new Methods();
        String query = "DELETE FROM `users`  WHERE `id` = '" +id+"'";
                n.executeSQlQuery(query, "Deleted");
              clear();
       
       
   }
    
    private void insertUserDetails(){
        
        Methods m= new Methods();
        String SirName= this. txtSirName.getText();
        String fullSirName=nametitle+" "+SirName;
        String uniq=accounttype+group;
             String query = "INSERT INTO `users`(`id`,`accountno`, `fname`, "
                     + "`sname`,`Phone`,`uniq`,`email`,`address`,`county`,`town`,`occupation`,"
                     + "`maritalstatus`,`spaucefname`,`spaucesname`,`spauceid`,`spaucephone`,`acounttype`,`group`,`updated_at`,`imgurl`) VALUES ("
                     + "'" + this.txtId.getText() + "','" + this.txtAccountNo.getText() + "',"
                     + "'" +fullSirName + "','" + this.txtOtherName.getText() + "','" + this.txtPhoneNo.getText() + "',"
                     + "'" + uniq + "','" + this.txtEmail.getText() + "','" + this. txtAddress.getText() + "',"
                     + "'" + this.txtCounty.getText() + "','" + this.txtTown.getText() + "',"
                     + "'" + this.txtOccupation.getText() + "','" + this.maritalStatus + "','" + this.txtSirSpouceName.getText() + "',"
                     + "'" + this.txtSpouceName.getText() + "','" + this.txtSpouceID.getText() + "','" + this.txtSpouceMobile.getText() + "',"
                     + "'" + this.accounttype + "','" + this.group + "',now(),"
                     + "'" + this.fileurlp + "')";

            m.executeSQlQuery(query, "Inserted");
            clear();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboMarital;
    private javax.swing.JComboBox ComboSalutation;
    private javax.swing.JButton btnAttachPhoto;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCounty;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtOtherName;
    private javax.swing.JTextField txtPeronId;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSirName;
    private javax.swing.JTextField txtSirSpouceName;
    private javax.swing.JTextField txtSpouceID;
    private javax.swing.JTextField txtSpouceMobile;
    private javax.swing.JTextField txtSpouceName;
    private javax.swing.JTextField txtTown;
    // End of variables declaration//GEN-END:variables
private void txtFieldsCntrl() {
        jComboBoxGroup.setEnabled(false);
        this.txtSirName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtOtherName.requestFocus();
            }
        });
        this.txtOtherName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtId.requestFocus();
            }
        });
        this.txtId.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtPhoneNo.requestFocus();
            }
        });
        this.txtPhoneNo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtEmail.requestFocus();
            }
        });
        this.txtEmail.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtAddress.requestFocus();
            }
        });
        this.txtAddress.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtCounty.requestFocus();
            }
        });
        this.txtCounty.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtTown.requestFocus();
            }
        });
        this.txtTown.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtOccupation.requestFocus();
            }
        });
        this.txtOccupation.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
               // txtSirSpouceName.requestFocus();
            }
        });
        this.txtSirSpouceName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtSpouceName.requestFocus();
            }
        });
        this.txtSpouceName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtSpouceID.requestFocus();
            }
        });
        this.txtSpouceID.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
                txtSpouceMobile.requestFocus();
            }
        });
        this.txtPeronId.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent b) {
              fetchUserDetails(txtPeronId.getText(), "id");
            }
        });
    }

    private void clear() {
        txtSirName.setText(null);
        txtOtherName.setText(null);
        txtId.setText(null);
        txtPhoneNo.setText(null);
        txtEmail.setText(null);
        txtAddress.setText(null);
        txtCounty.setText(null);
        txtTown.setText(null);
        txtOccupation.setText(null);
        txtSirSpouceName.setText(null);
        txtSpouceName.setText(null);
        txtSpouceID.setText(null);
        txtSpouceMobile.setText(null);
        txtAccountNo.setText("Auto");
        img.setIcon(null);
        filePath = null;
        fileurlp = null;
        ComboSalutation.setSelectedIndex(0);
        ComboMarital.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
        jComboBoxGroup.setSelectedIndex(0);
        txtPeronId.setText("");
    }
}
