/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imua.development;

import java.awt.Color;
import java.awt.Container;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kamau
 */
public class garanters extends javax.swing.JFrame {
static String id=null;
     String idd;
     String name;
     String phone; 
//int step;
    /**
     * Creates new form NewJFrame
     */
    public garanters() {
        initComponents();
        setTilteImage();
       // String id=null;
        //getiD();
        
    }
    private void setTilteImage(){
        try {
            Methods n=new Methods();
            String t= n.setTitle();
            this.setTitle(t);
            String i=n.setIconImage();
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(i)));
            
            String col=n.selectcolor();
            Color c=new Color(Integer.parseInt(col));
             Container cont=this.getContentPane();
            cont.setBackground(c);
          //  jPanel2.setBackground(c);
        } catch (Exception ex) {
            Logger.getLogger(Accgroups.class.getName()).log(Level.SEVERE, null, ex);
        }
}
  public   void getiD(){
     
      JOptionPane.showMessageDialog(null, id);
    }
    garanters(String text) {
       id=text;
       JOptionPane.showMessageDialog(null, id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGaranteeName = new javax.swing.JTextField();
        txtGaranteeID = new javax.swing.JTextField();
        txtGaranteeMobile = new javax.swing.JTextField();
        txtGaranteeName2 = new javax.swing.JTextField();
        txtGaranteeID2 = new javax.swing.JTextField();
        txtGaranteeMobile2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtGaranteeName3 = new javax.swing.JTextField();
        txtGaranteeID3 = new javax.swing.JTextField();
        txtGaranteeMobile3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtGaranteeName4 = new javax.swing.JTextField();
        txtGaranteeID4 = new javax.swing.JTextField();
        txtGaranteeMobile4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtGaranteeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeNameActionPerformed(evt);
            }
        });

        txtGaranteeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeIDActionPerformed(evt);
            }
        });

        txtGaranteeMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeMobileActionPerformed(evt);
            }
        });

        txtGaranteeName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeName2ActionPerformed(evt);
            }
        });

        txtGaranteeID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeID2ActionPerformed(evt);
            }
        });

        txtGaranteeMobile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeMobile2ActionPerformed(evt);
            }
        });

        jLabel12.setText("1. Garantee");

        jLabel13.setText("ID No.");

        jLabel14.setText("Mobile No.");

        jLabel15.setText("2. Garantee");

        jLabel16.setText("ID No.");

        jLabel17.setText("Mobile No.");

        txtGaranteeName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeName3ActionPerformed(evt);
            }
        });

        txtGaranteeID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeID3ActionPerformed(evt);
            }
        });

        txtGaranteeMobile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeMobile3ActionPerformed(evt);
            }
        });

        jLabel18.setText("3. Garantee");

        jLabel19.setText("ID No.");

        jLabel20.setText("Mobile No.");

        txtGaranteeName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeName4ActionPerformed(evt);
            }
        });

        txtGaranteeID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeID4ActionPerformed(evt);
            }
        });

        txtGaranteeMobile4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaranteeMobile4ActionPerformed(evt);
            }
        });

        jLabel21.setText("4. Garantee");

        jLabel24.setText("ID No.");

        jLabel25.setText("Mobile No.");

        lbltitle.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lbltitle.setText("Garantee Information Form");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGaranteeID2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeName2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeMobile2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGaranteeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGaranteeName3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeID3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeMobile3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGaranteeName4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeID4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGaranteeMobile4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtGaranteeID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtGaranteeMobile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtGaranteeMobile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGaranteeID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtGaranteeMobile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGaranteeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeNameActionPerformed

    private void txtGaranteeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeIDActionPerformed

    private void txtGaranteeMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeMobileActionPerformed

    private void txtGaranteeName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeName2ActionPerformed

    private void txtGaranteeID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeID2ActionPerformed

    private void txtGaranteeMobile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeMobile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeMobile2ActionPerformed

    private void txtGaranteeName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeName3ActionPerformed

    private void txtGaranteeID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeID3ActionPerformed

    private void txtGaranteeMobile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeMobile3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeMobile3ActionPerformed

    private void txtGaranteeName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeName4ActionPerformed

    private void txtGaranteeID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeID4ActionPerformed

    private void txtGaranteeMobile4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaranteeMobile4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaranteeMobile4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // String [] ids={txtGaranteeID.getText(),txtGaranteeID2.getText(),txtGaranteeID3.getText(), txtGaranteeID4.getText()};
        
        
       insert() ;
     //   checkIfExist(ids);
        //Main.a = 1;
        
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
       
    } 
//HashMap<String,String>guranter=new HashMap<String,String>();
 private void insert(){
 
     for(int a=0;a<=3;a++){
         if(a==0){
          idd=txtGaranteeID.getText();
        name=txtGaranteeName.getText();
          phone=txtGaranteeMobile.getText();
         
         }
         else if(a==1){
              idd=txtGaranteeID2.getText();
          name=txtGaranteeName2.getText();
          phone=txtGaranteeMobile2.getText();
             
         }
         else if (a==2) {
             idd=txtGaranteeID3.getText();
          name=txtGaranteeName3.getText();
          phone=txtGaranteeMobile3.getText();
         }
         else if(a==3){
          idd=txtGaranteeID4.getText();
          name=txtGaranteeName4.getText();
           phone=txtGaranteeMobile4.getText();
         }
         else{
             JOptionPane.showMessageDialog(null, "ERROR");
         }
        
         
            insertr(); 
         
     }
     
    
     
     
     
 }
 private void checkIfAgurantorAlready(String [] ids){
     
      String []notIn ={"ch"};
     for(int a=0;a<ids.length;a++){
         idd=ids[a];
        try
        {
            //get database connection details
           Methods n=new Methods();
            String stru=idd;
             //open connection
          Connection con = n.getConnection();
          String str="";
            
            str="select * from guranters where  id =?";
            
           PreparedStatement pst=con.prepareStatement(str);
         
           pst.setString(1, stru);
          
           ResultSet rs;
          // ResultSet rs1;
           rs=pst.executeQuery();
          
           if (rs.next())
               
          {
              notIn[a]=idd;
//              Object []options={"GO BACK","CONTINUE ANYWAY","CANCEL"};
//           int btn= JOptionPane.showOptionDialog(null, idd+" IS ALREADY A GURANTER ","CONFIRM",
//                    JOptionPane.DEFAULT_OPTION,
//                    JOptionPane.PLAIN_MESSAGE,null,options,options[0]);
//            if(btn==1){
//               insert();
//            }
//            else if(btn==2){
//         
//            }
//            else{
//                //clear();
//            }  
               
               
//          JOptionPane.showMessageDialog(null,"A PRODUCT WITH SUCH NAME  ("+jTextField_name.getText()+")  ALREADY EXIST \n "
//                  + " USE ANOTHER NAME OR UPDATE THE PRODUCTS IN QUESTION");
               
           }
           else
           {
           
            }
           con.close();
           rs.close();
           pst.close();

        }
        catch (Exception b)
        {
            System.err.println(b);
           // System.exit(1);
        }    
     }
      if(notIn.length!=0){
            Object []options={"GO BACK","CONTINUE ANYWAY","CANCEL"};
           int btn= JOptionPane.showOptionDialog(null, idd+" IS ALREADY A GURANTER","CONFIRM",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.PLAIN_MESSAGE,null,options,options[0]);
          switch (btn) {
              case 1:
                  insert();
                  break;
              case 2:
                  clear();
                  break;
              default:
                  break;  
          }
     }
     else{
         insert();
     }
 }
 private void checkIfExist(String [] ids){
     String []notIn={"ch"} ;
     for(int a=0;a<ids.length;a++){
         idd=ids[a];
     try
        {
            //get database connection details
           Methods n=new Methods();
            String stru=idd;
             //open connection
          Connection con = n.getConnection();
          String str="";
            
            str="select * from users where  id =?";
            
           PreparedStatement pst=con.prepareStatement(str);
         
           pst.setString(1, stru);
          
           ResultSet rs;
          // ResultSet rs1;
           rs=pst.executeQuery();
          
           if (rs.next())
               
           {
       //notIn[a]=idd;
//                 Object []options={"GO BACK","CONTINUE ANYWAY","CANCEL"};
//           int btn= JOptionPane.showOptionDialog(null, idd+" IPERSON NOT FOUND ","CONFIRM",
//                    JOptionPane.DEFAULT_OPTION,
//                    JOptionPane.PLAIN_MESSAGE,null,options,options[0]);
//            if(btn==1){
//                checkIfAgurantorAlready();
//            }
//            else if(btn==2){
//             clear();
//            }
//            else{
//                //clear();
//            }  
////          JOptionPane.showMessageDialog(null,"A PRODUCT WITH SUCH NAME  ("+jTextField_name.getText()+")  ALREADY EXIST \n "
////                  + " USE ANOTHER NAME OR UPDATE THE PRODUCTS IN QUESTION");
               
           }
           else
           {
                notIn[a]=idd;
            }
           con.close();
           rs.close();
           pst.close();

        }
        catch (Exception b)
        {
            System.err.println(b);
           // System.exit(1);
        }  
     
     
     
     
     }
     if(notIn.length!=0){
            Object []options={"GO BACK","CONTINUE ANYWAY","CANCEL"};
           int btn= JOptionPane.showOptionDialog(null, idd+" IPERSON NOT FOUND ","CONFIRM",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.PLAIN_MESSAGE,null,options,options[0]);
         switch (btn) {
             case 1:
                 checkIfAgurantorAlready(ids);
                 break;
             case 2:
                 clear();
                 break;
             default:
                 break;  
         }
     }
     else{
         checkIfAgurantorAlready(ids);
     }
     
 }
 private  void insertr(){
      try {
            Methods m=new Methods();
            try (Connection connection = m.getConnection()) {
                String query = "INSERT INTO `guranters`(`id`, `name`,`phone`,`gurantee`) VALUES ('" + this.idd + "','" + name + "','" + phone+ "','" + id + "')";
                
                try (PreparedStatement pst = connection.prepareStatement(query)) {
                    pst.executeUpdate(query);
                    
                    
                    pst.close();
                    connection.close();
                }
            }
            JOptionPane.showMessageDialog(null, "Succesfully filled ");
             loanform.y=1;
             //clear();
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Error ");
            Logger.getLogger(Accgroups.class.getName()).log(Level.SEVERE, null, ex);
        }
 } 
 public void clear(){
   txtGaranteeID.setText("");
    txtGaranteeID2.setText("");
  txtGaranteeID3.setText("");
  txtGaranteeID4.setText("");
  txtGaranteeMobile.setText("");
  txtGaranteeMobile2.setText("");
  txtGaranteeMobile3.setText("");
  txtGaranteeMobile4.setText("");
  txtGaranteeName.setText("");
  txtGaranteeName2.setText("");
   txtGaranteeName3.setText("");
   txtGaranteeName4.setText("");
     
     
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(garanters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(garanters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(garanters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(garanters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new garanters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtGaranteeID;
    private javax.swing.JTextField txtGaranteeID2;
    private javax.swing.JTextField txtGaranteeID3;
    private javax.swing.JTextField txtGaranteeID4;
    private javax.swing.JTextField txtGaranteeMobile;
    private javax.swing.JTextField txtGaranteeMobile2;
    private javax.swing.JTextField txtGaranteeMobile3;
    private javax.swing.JTextField txtGaranteeMobile4;
    private javax.swing.JTextField txtGaranteeName;
    private javax.swing.JTextField txtGaranteeName2;
    private javax.swing.JTextField txtGaranteeName3;
    private javax.swing.JTextField txtGaranteeName4;
    // End of variables declaration//GEN-END:variables
}
