/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imua.development;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kimani kogi
 */
public class loantypes extends javax.swing.JFrame {

    /**
     * Creates new form loantypes
     */
    public loantypes() {
        initComponents();
        setTilteImage();
        findUsers();
    }
     private void setTilteImage(){
     Methods n=new Methods();
    String t= n.setTitle();
    this.setTitle(t);
    String i=n.setIconImage();
    this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(i)));
}
  public ArrayList<loantypesholder> ListUsers()
  {
    ArrayList<loantypesholder> usersList = new ArrayList();
    try
    {
        Methods m=new Methods();
        Connection con = m.getConnection();
     // Connection con = getConnection();
      Statement st = con.createStatement();
      String searchQuery = "SELECT * FROM `accounttypes`";
      ResultSet rs = st.executeQuery(searchQuery);
      while (rs.next())
      {
        loantypesholder user = new loantypesholder(rs.getString("id"), rs.getString("name"),rs.getString("rate"),rs.getString("appfee"),rs.getString("penalt"),rs.getString("balance")
        ,rs.getString("lv1"),rs.getString("lv2"),rs.getString("lv3"),rs.getString("lv4"),rs.getString("lv5"),rs.getString("lv6"),rs.getString("lv7"),
        rs.getString("lv8"),rs.getString("lv9"),rs.getString("lv10"));
        
        usersList.add(user);
      }
      st.close();
      rs.close();
      con.close();
    }
    catch (Exception ex)
    {
      System.out.println(ex.getMessage());
    }
    return usersList;
  }
  
  public void findUsers()
  {
    ArrayList<loantypesholder> users = ListUsers();
    DefaultTableModel model = new DefaultTableModel();
    
    model.setColumnIdentifiers(new Object[] { "ID", "Name","Rate","Aplication","Penalty","Balance","<5,000","<10,000","<15,000","<20,000","<25,000","<30,000",
        "<40,000","<50,000","<60,000","+60,000" });
    Object[] row = new Object[16];
    for (int i = 0; i < users.size(); i++)
    {
      row[0] = ((loantypesholder)users.get(i)).getId();
      row[1] = ((loantypesholder)users.get(i)).getName();
        row[2] = ((loantypesholder) users.get(i)).getRate();
        row[3] = ((loantypesholder) users.get(i)).getAppFee();
        row[4] = ((loantypesholder) users.get(i)).getPenalty();
        row[5] = ((loantypesholder) users.get(i)).getBalance();
        row[6] = ((loantypesholder) users.get(i)).getLv1();
        row[7] = ((loantypesholder) users.get(i)).getLv2();
        row[8] = ((loantypesholder) users.get(i)).getLv3();
        row[9] = ((loantypesholder) users.get(i)).getLv4();
        row[10] = ((loantypesholder) users.get(i)).getLv5();
        row[11] = ((loantypesholder) users.get(i)).getLv6();
        row[12] = ((loantypesholder) users.get(i)).getLv7();
        row[13] = ((loantypesholder) users.get(i)).getLv8();
        row[14] = ((loantypesholder) users.get(i)).getLv9();
        row[15] = ((loantypesholder) users.get(i)).getLv10();
      
     
      
      model.addRow(row);
    }
    this.table.setModel(model);
  }
   public void executeSQlQuery(String query, String message)
  {
   Methods m=new Methods();
        Connection con = m.getConnection();
    try
    {
      Statement st = con.createStatement();
      if (st.executeUpdate(query) == 1)
      {
        DefaultTableModel model = (DefaultTableModel)this.table.getModel();
        
        model.setRowCount(0);
        clear();
        findUsers();
        
        JOptionPane.showMessageDialog(null,  message + " Succefully");
      }
      else
      {
        JOptionPane.showMessageDialog(null, " Not " + message);
       
      }
      st.close();
      con.close();
    }
    catch (Exception ex)
    {
      ex.printStackTrace();
    }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField14 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        trate = new javax.swing.JTextField();
        tappfee = new javax.swing.JTextField();
        tpenalty = new javax.swing.JTextField();
        tbalance = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tlv2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tlv1 = new javax.swing.JTextField();
        tlv4 = new javax.swing.JTextField();
        tlv3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tlv6 = new javax.swing.JTextField();
        tlv5 = new javax.swing.JTextField();
        tlv7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tlv8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tlv9 = new javax.swing.JTextField();
        tlv10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTextField14.setText("jTextField14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("INFORMATION");

        jLabel2.setText("NAME");

        tlv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlv4ActionPerformed(evt);
            }
        });

        tlv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlv3ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jLabel4.setText("RATE");

        jLabel5.setText("APPLICATION FEE");

        jLabel6.setText("PENALTY");

        jLabel7.setText("*BALANCE");

        jLabel8.setText("<5000");

        jLabel9.setText("<10,000");

        jLabel10.setText("<15000");

        jLabel11.setText("<20,000");

        jLabel12.setText("<30,000");

        tlv6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlv6ActionPerformed(evt);
            }
        });

        jLabel13.setText("<25000");

        jLabel14.setText("<40,000");

        jLabel15.setText("<50,000");

        jLabel16.setText("<60,000");

        jLabel17.setText("60001+");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tpenalty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tlv1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(trate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(tlv9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tlv3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tlv7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tlv5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tappfee)
                                .addComponent(tname)
                                .addComponent(tbalance)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addComponent(tlv2)
                                .addComponent(jLabel12)
                                .addComponent(jLabel17)
                                .addComponent(tlv10)
                                .addComponent(tlv8)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addComponent(tlv6)
                                .addComponent(tlv4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tappfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlv6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tlv8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlv7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlv9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlv10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tlv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlv4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlv4ActionPerformed

    private void tlv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlv3ActionPerformed

    private void tlv6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlv6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlv6ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = this.table.getSelectedRow();

        TableModel model = this.table.getModel();

        this.tid.setText(model.getValueAt(i, 0).toString());

        this.tname.setText(model.getValueAt(i, 1).toString());
      //  this.tname.setText(model.getValueAt(i, 2).toString());
        this.trate.setText(model.getValueAt(i, 2).toString());
        this.tappfee.setText(model.getValueAt(i, 3).toString());
        
        this.tpenalty.setText(model.getValueAt(i, 4).toString());
        this.tbalance.setText(model.getValueAt(i, 5).toString());
        this.tlv1.setText(model.getValueAt(i, 6).toString());
        this.tlv2.setText(model.getValueAt(i, 7).toString());
        this.tlv3.setText(model.getValueAt(i, 8).toString());
        this.tlv4.setText(model.getValueAt(i, 9).toString());
        this.tlv5.setText(model.getValueAt(i, 10).toString());
        this.tlv6.setText(model.getValueAt(i, 11).toString());
        this.tlv7.setText(model.getValueAt(i, 12).toString());
        this.tlv8.setText(model.getValueAt(i, 13).toString());
        this.tlv9.setText(model.getValueAt(i, 14).toString());
          this.tlv10.setText(model.getValueAt(i, 15).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
check(1) ;      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
check(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
check(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       Main.a = 1;
    }//GEN-LAST:event_formWindowClosed
private void insert(){
    try
      {
        String stru = this.tid.getText().toString();
        Methods m=new Methods();
        Connection con = m.getConnection();
        String str = "";
        
        str = "select * from accounttypes where  id =?";
        
        PreparedStatement pst = con.prepareStatement(str);
        
        pst.setString(1, stru);
        
        ResultSet rs = pst.executeQuery();
        if (rs.next())
        {
          JOptionPane.showMessageDialog(null, " SUCH  ID  (" + this.tid.getText() + ")  ALREADY EXIST \n " );
        }
        else
        {
String query = "INSERT INTO `accounttypes`(`id`, `name`, `rate`,`appfee`,`penalt`,`balance`,`lv1`,`lv2`,`lv3`,`lv4`,`lv5`,`lv6`,`lv7`,`lv8`,`lv9`,`lv10`)"
 + " VALUES ('" + this.tid.getText() + "','" + this.tname.getText() + "','" + this.trate.getText() + "','" + this.tappfee.getText() + "','" + this.tpenalty.getText() + "'"
        + ",'" + this.tbalance.getText() + "','" + this.tlv1.getText() + "','" + this.tlv2.getText() + "','" + this.tlv3.getText() + "','" + this.tlv4.getText() + "'"
        + ",'" + this.tlv5.getText() + "','" + this.tlv6.getText() + "','" + this.tlv7.getText() + "','" + this.tlv8.getText() + "','" + this.tlv9.getText() + "'"
        + ",'" + this.tlv10.getText() + "')";
          
          executeSQlQuery(query, "Inserted");
        }
        con.close();
        rs.close();
        pst.close();
      }
      catch (Exception a)
      {
        System.err.println(a);
      }
}
private void update(){
    String query = "UPDATE `accounttypes` SET `name`='" + this.tname.getText() + "',`rate`= '" + this.trate.getText() + "'"
            + ",`appfee`= '" + this.tappfee.getText() + "',`penalt`= '" + this.tpenalty.getText() + "',`balance`= '" + this.tbalance.getText() + "',"
            + "`lv1`= '" + this.tlv1.getText() + "'"
            + ",`lv2`= '" + this.tlv2.getText() + "',`lv3`= '" + this.tlv3.getText() + "',`lv4`= '" + this.tlv4.getText() + "',`lv5`= '" + this.tlv5.getText() + "'"
            + ",`lv6`= '" + this.tlv6.getText() + "',`lv7`= '" + this.tlv7.getText() + "',`lv8`= '" + this.tlv8.getText() + "',`lv9`= '" + this.tlv9.getText() + "'"
            + ",`lv10`= '" + this.tlv10.getText() + "'";
      
      executeSQlQuery(query, "Updated");
}
public void delete(){
    String query = "DELETE FROM `accounttypes` WHERE id = " + this.tid.getText();
    
    executeSQlQuery(query, "Deleted");
}
public void check(int a){
    if(tid.getText().isEmpty()||
        tname.getText().isEmpty()||
        trate.getText().isEmpty()||
            tappfee.getText().isEmpty()||
            tpenalty.getText().isEmpty()||
            tbalance.getText().isEmpty()||
            tlv1.getText().isEmpty()||
            tlv2.getText().isEmpty()||
            tlv3.getText().isEmpty()||
            tlv4.getText().isEmpty()||
            tlv5.getText().isEmpty()||
            tlv6.getText().isEmpty()||
            tlv7.getText().isEmpty()||
            tlv8.getText().isEmpty()||
            tlv9.getText().isEmpty()||
            tlv10.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Empty fields Detected");
        
    }
    else{
        switch (a){
            case 1:
                insert();
                break;
            case 2:
                update();
                break;
            case 3:
                delete();
                break;
            default:
                JOptionPane.showMessageDialog(null, "ERROR");
            
        }
    }
}
public void clear(){
    tid.setText("");
    tname.setText("");
    trate.setText("");
    tappfee.setText("");
    tpenalty.setText("");
    tbalance.setText("");
    tlv1.setText("");
    tlv2.setText("");
    tlv3.setText("");
    tlv4.setText("");
    tlv5.setText("");
    tlv6.setText("");
    tlv7.setText("");
    tlv8.setText("");
    tlv9.setText("");
    tlv10.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loantypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loantypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loantypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loantypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loantypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTable table;
    private javax.swing.JTextField tappfee;
    private javax.swing.JTextField tbalance;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tlv1;
    private javax.swing.JTextField tlv10;
    private javax.swing.JTextField tlv2;
    private javax.swing.JTextField tlv3;
    private javax.swing.JTextField tlv4;
    private javax.swing.JTextField tlv5;
    private javax.swing.JTextField tlv6;
    private javax.swing.JTextField tlv7;
    private javax.swing.JTextField tlv8;
    private javax.swing.JTextField tlv9;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tpenalty;
    private javax.swing.JTextField trate;
    // End of variables declaration//GEN-END:variables
}
