/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imua.development.BackupRestore;

import com.mysql.jdbc.PreparedStatement;
import imua.development.Main;
import imua.development.Methods;
import java.awt.Color;
import java.awt.Container;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;

/**
 *
 * @author kimani kogi
 */
public class Restore extends javax.swing.JFrame {
 Methods m=new Methods();
 String loans=null;
    /**
     * Creates new form Restore
     */
    public Restore() {
        initComponents();
        setTilteImage();
    }
    public Color setTilteImage(){
        Color c=null;
        try {
            Methods n=new Methods();
            String t= n.setTitle();
            this.setTitle(t);
            String i=n.setIconImage();
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(i)));
            
            String col=n.selectcolor();
             c=new Color(Integer.parseInt(col));
            jPanel1.setBackground(c);
            Container cont=this.getContentPane();
            cont.setBackground(c);
            jPanel2.setBackground(c);
            jPanel3.setBackground(c);
            this.setForeground(c);
        } catch (Exception ex) {
            Logger.getLogger(Restore.class.getName()).log(Level.SEVERE, null, ex);
        }
        return c;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jtfFileLocation = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jtfFileLocations = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Restore"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("XLS"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loans", "OrgAccount", "Customers", "LoanTypes", "Guranters", "Accounts", "Groups", "LoansArchives", "Prefrences", "Applications", "Transactions" }));
        jComboBox1.setEnabled(false);
        jComboBox1.setFocusCycleRoot(true);

        jButton1.setText("RESTORE");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfFileLocation.setEditable(false);
        jtfFileLocation.setText("Disabled in favour of SQL format Which is more accurate");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addComponent(jtfFileLocation))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jtfFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("SQL"));

        jButton2.setText("RESTORE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtfFileLocations.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfFileLocations, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jtfFileLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String fileSeparator = System.getProperty("file.separator");
JFileChooser chooser = new JFileChooser();
String path=null;
//set JFileChooser default path
chooser.setCurrentDirectory(new java.io.File("."));
//set JFileChooser title
chooser.setDialogTitle("open");
//use as you need DIRECTORIES_ONLY, FILES_ONLY etc
chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
 
//false, if you want to view all kind of file type in JFileChooser
//true, if you want to create FileFilter and open only file type you want to be view in JFileChooser
chooser.setAcceptAllFileFilterUsed(false);
 
if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
    //write selected path inside JTextField
    jtfFileLocations.setText(chooser.getSelectedFile().getPath()+fileSeparator);
    //students=getText(chooser.getSelectedFile().getPath()+fileSeparator);
    path=jtfFileLocations.getText();
    System.out.println(""+path+"");
    restorSql(path);
} else {
    System.out.println("No Selection");
}       
    }//GEN-LAST:event_jButton2ActionPerformed
public void restorSql(String path){
        try {
            Connection con = m.getConnection();
            /* Note that con is a connection to database, and not the server.
            if You have a connection to the server, the first command in the dumpfile should be the
            USE db_name; */
            String q = "";
            Statement st = con.createStatement();
            try {
                File f = new File(path); // source path is the absolute path of dumpfile.
                
                BufferedReader bf = new BufferedReader(new FileReader(f));
                String line = null,old="";
                line = bf.readLine();
                while (line != null) {
                    q = q + line + "\n";
                  //  if(line.endsWith(";")){
                  //      st.executeUpdate(old+line);
                  ///      old="";
                  //  }
                  //  else
                  //      old=old+"\n"+line;
                    line = bf.readLine();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            String []commands=q.split(";");
            try{
                for(String s:commands){
                    st.execute(s);
                   
                   // 
                }
                JOptionPane.showMessageDialog(null, "DONE", "MESSAGE",JOptionPane.PLAIN_MESSAGE);
                 jtfFileLocations.setText("");
            }
            catch(Exception a){
                a.printStackTrace();
            }
            con.close();
        } catch (SQLException ex) {
         Logger.getLogger(Restore.class.getName()).log(Level.SEVERE, null, ex);
   }
}
    
    public void restoreLoans(){
//    
//    
//    String fileSeparator = System.getProperty("file.separator");
//JFileChooser chooser = new JFileChooser();
////set JFileChooser default path
//chooser.setCurrentDirectory(new java.io.File("."));
////set JFileChooser title
//chooser.setDialogTitle("open");
////use as you need DIRECTORIES_ONLY, FILES_ONLY etc
//chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
// 
////false, if you want to view all kind of file type in JFileChooser
////true, if you want to create FileFilter and open only file type you want to be view in JFileChooser
//chooser.setAcceptAllFileFilterUsed(false);
// 
//if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
//    //write selected path inside JTextField
//    jtfFileLocation.setText(chooser.getSelectedFile().getPath()+fileSeparator);
//    //students=getText(chooser.getSelectedFile().getPath()+fileSeparator);
//    loans=jtfFileLocation.getText();
//    System.out.println(""+loans+"");
//} else {
//    System.out.println("No Selection");
//}
//try{
//    DataFormatter forma =new DataFormatter();
//            
//             Connection con = m.getConnection();
//              con.setAutoCommit(false);
//            PreparedStatement pstm = null ;
//             //PreparedStatement pstm1 = null ;
//           // this.fileurlp = this.student.replace("\\", "\\\\");
//            FileInputStream input = new FileInputStream(""+loans+"");
//            POIFSFileSystem fs = new POIFSFileSystem( input );
//            HSSFWorkbook wb = new HSSFWorkbook(fs);
//            HSSFSheet sheet = wb.getSheetAt(0);
//            Row row;
//            for(int i=1; i<=sheet.getLastRowNum(); i++){
//                row = sheet.getRow(i);
//                 + "'" + id+ "'"
//             + ",'" + lnId+ "'"
//            
//             + ",'" + lnType+ "'"
//              + ",'" + applicable+ "'"
//             + ",'" + installmentamount + "'"
//             + ",'" + installmentno+"'"
//             + ",'" + periodtype + "'"
//             + ",'" + frequency+ "'"
//             + ",'" + targetdate + "'"
//             + ",'"+loanAmount+"'"
//             + ",'"+loanrequested+"'"
//              
//             + ",'"+loanamount+"'"
//            
//             + ",'"+defaultacc+"'"
//             + ",'"+appfee+"'"
//             + ",'"+todaypay+"'"
//              + ",'"+nxp+"'"
//             + ",'"+givenon+"'"
//             + ",'"+paidon+"')";
//                Cell sid=row.getCell(0);
//                Cell slnId=row.getCell(1);
//                Cell slnType=row.getCell(2);
//                Cell sapplicable=row.getCell(3);
//                Cell sinstallmentamount=row.getCell(4);
//                Cell sinstallmentno=row.getCell(5);
//                      String sid=forma.formatCellValue(sidc);
//                      String fname=forma.formatCellValue(fnamec);
//                      String lastname=forma.formatCellValue(lastnamec);
//                      String form=forma.formatCellValue(formc);
//                      String classs=forma.formatCellValue(classc);
//                      String imgurlK=forma.formatCellValue(imagec);
//                
//                String sid =   row.getCell(0).getStringCellValue();
//                String fname = row.getCell(1).getStringCellValue();
//                String lastname = row.getCell(2).getStringCellValue();
//                String form = row.getCell(3).getStringCellValue();
//                String classs = row.getCell(4).getStringCellValue();
//                String imgurlK = row.getCell(5).getStringCellValue();
//                
//               // String imgurl =imgurlK.replace("\\", "\\\\");
//                //String sql1="DROP TABLE IF EXISTS students";
//                
//                String query = "INSERT INTO loans("
//             + "`id`,"
//             + "`loanid`,"
//             
//             + "`loantype`,"
//            +"`applicable`,"
//             + " `installmentamount`"
//             + ",`installmentsno`"
//             + ",`periodtype`"
//             + ",`frequencyperperiod`"
//             + ",`targetdate`"
//             + ",`loanAmount`"
//              + ",`loanRequested`"
//             + ",`loanbalance`"
//             + ",`defaultacc`"
//             + ",`applicationfee`"
//             + ",`todaypay`"
//              + ",`nxp`"
//             + ",`givenOn`"
//             + ",`paidon`)"
//             + " VALUES ("
//             + "'" + id+ "'"
//             + ",'" + lnId+ "'"
//            
//             + ",'" + lnType+ "'"
//              + ",'" + applicable+ "'"
//             + ",'" + installmentamount + "'"
//             + ",'" + installmentno+"'"
//             + ",'" + periodtype + "'"
//             + ",'" + frequency+ "'"
//             + ",'" + targetdate + "'"
//             + ",'"+loanAmount+"'"
//             + ",'"+loanrequested+"'"
//              
//             + ",'"+loanamount+"'"
//            
//             + ",'"+defaultacc+"'"
//             + ",'"+appfee+"'"
//             + ",'"+todaypay+"'"
//              + ",'"+nxp+"'"
//             + ",'"+givenon+"'"
//             + ",'"+paidon+"')";
//                
//                
//                
//                //String sql = "INSERT INTO students VALUES('"+sid+"','"+fname+"','"+lastname+"','"+form+"','"+classs+"','"+imgurl+"')";
//              // pstm1=(PreparedStatement) con.prepareStatement(sql1);
//                pstm = (PreparedStatement) con.prepareStatement(query);
//               //  pstm1.execute();
//                pstm.execute();
//                System.out.println("Import rows "+i);
//            }
//            con.commit();
//            pstm.close();
//            
//            con.close();
//            input.close();
//            JOptionPane.showMessageDialog(null, "Success import excel to mysql table"
//               );
//            System.out.println("Success import excel to mysql table");
//        }catch(SQLException ex){
//             JOptionPane.showMessageDialog(null, "error import excel to mysql table");
//            System.out.println(ex);
//        }catch(IOException ioe){
//            System.out.println(ioe);
//             JOptionPane.showMessageDialog(null, "error import excel to mysql table");
//        }
//
//    
//    
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtfFileLocation;
    private javax.swing.JTextField jtfFileLocations;
    // End of variables declaration//GEN-END:variables
}
